#!/usr/bin/env python3
"""Build the AGENTS.md map in .agents/map/ from the related_files headers.

Opt-in: run this only after a human has explicitly agreed to it
(see .agents/skills/agents-map/SKILL.md). Nothing runs it automatically.

Writes two files:

  .agents/map/graph.json  every AGENTS.md, its parent and children, and each
                          related_files path with its kind (agents, file,
                          folder or missing)
  .agents/map/MAP.md      Mermaid diagrams of the same graph, which GitHub renders

The output has no timestamps, so rebuilding an unchanged graph changes nothing.

Usage: python .github/scripts/build_agents_map.py [--check] [--root DIR]
  --check  exit 1 if .agents/map/ is missing or out of date, without writing
Needs PyYAML.
"""

from __future__ import annotations

import argparse
import json
import posixpath
import sys
from collections import defaultdict
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parent))
from check_agents_md import NAME, list_files, nearest_parent, split_header  # noqa: E402

MAP_DIR = ".agents/map"
OUTPUTS = (f"{MAP_DIR}/graph.json", f"{MAP_DIR}/MAP.md")
SCRIPT = ".github/scripts/build_agents_map.py"
SKILL = ".agents/skills/agents-map/SKILL.md"


def read_graph(root: Path) -> list[dict]:
    # Count the map's own outputs as present, so an AGENTS.md that lists them gets
    # the same map whether or not they have been written yet.
    all_files = sorted(set(list_files(root)) | set(OUTPUTS))
    files = set(all_files)
    folders: set[str] = set()
    for p in all_files:
        folder = posixpath.dirname(p)
        while folder and folder not in folders:
            folders.add(folder)
            folder = posixpath.dirname(folder)
    agents = [p for p in all_files if posixpath.basename(p) == NAME]
    present = set(agents)

    nodes = []
    for path in agents:
        header, _, problem = split_header((root / path).read_text(encoding="utf-8"))
        entries = header.get("related_files") if header and not problem else None
        related = []
        for entry in entries if isinstance(entries, list) else []:
            if not isinstance(entry, str) or not entry.strip():
                continue
            entry = entry.strip().rstrip("/")
            if posixpath.basename(entry) == NAME and entry in present:
                kind = "agents"
            elif entry in files:
                kind = "file"
            elif entry in folders:
                kind = "folder"
            else:
                kind = "missing"
            related.append({"path": entry, "kind": kind})
        nodes.append({
            "path": path,
            "parent": nearest_parent(path, present),
            "children": sorted(p for p in agents if p != path and nearest_parent(p, present) == path),
            "header_ok": problem is None and isinstance(entries, list),
            "related_files": related,
        })
    return nodes


def mermaid_label(path: str) -> str:
    return '"' + path.replace('"', "#quot;") + '"'


def render_markdown(nodes: list[dict]) -> str:
    total = sum(len(n["related_files"]) for n in nodes)
    missing = sum(1 for n in nodes for r in n["related_files"] if r["kind"] == "missing")
    listed_by = defaultdict(list)
    for n in nodes:
        for r in n["related_files"]:
            if r["kind"] != "agents":
                listed_by[r["path"]].append(n["path"])

    out = [
        "# AGENTS.md map",
        "",
        f"Generated by `{SCRIPT}` from the `related_files` headers of every AGENTS.md.",
        f"Don't edit it by hand; rebuild it as described in `{SKILL}`.",
        "",
        f"{len(nodes)} AGENTS.md file(s) listing {total} related path(s), {missing} of them missing.",
        "",
        "## AGENTS.md links",
        "",
        "A line joins two AGENTS.md files when either lists the other.",
        "",
        "```mermaid",
        "graph LR",
    ]
    ids = {n["path"]: f"a{i}" for i, n in enumerate(nodes)}
    for n in nodes:
        out.append(f"  {ids[n['path']]}[{mermaid_label(n['path'])}]")
    pairs = sorted({tuple(sorted((n["path"], r["path"])))
                    for n in nodes for r in n["related_files"] if r["kind"] == "agents"})
    for a, b in pairs:
        out.append(f"  {ids[a]} --- {ids[b]}")
    out += ["```", ""]

    shared = {p: owners for p, owners in listed_by.items() if len(owners) > 1}
    if shared:
        out += ["## Paths listed by more than one AGENTS.md", "",
                "| Path | Listed by |", "| --- | --- |"]
        for p in sorted(shared):
            out.append(f"| `{p}` | {', '.join(f'`{o}`' for o in shared[p])} |")
        out.append("")

    for n in nodes:
        out += [f"## `{n['path']}`", ""]
        if not n["header_ok"]:
            out += ["Header is missing or malformed; run `.github/scripts/check_agents_md.py`.", ""]
            continue
        out.append(f"Parent: {'`' + n['parent'] + '`' if n['parent'] else 'none'}. "
                   f"Children: {', '.join(f'`{c}`' for c in n['children']) or 'none'}.")
        out += ["", "```mermaid", "graph LR",
                "  classDef agents fill:#dbeafe,stroke:#1d4ed8",
                "  classDef missing fill:#fee2e2,stroke:#b91c1c,stroke-dasharray:4",
                f"  self[{mermaid_label(n['path'])}]:::agents"]
        for i, r in enumerate(n["related_files"]):
            style = {"agents": ":::agents", "missing": ":::missing"}.get(r["kind"], "")
            out.append(f"  self --> r{i}[{mermaid_label(r['path'])}]{style}")
        out += ["```", ""]
    return "\n".join(out).rstrip("\n") + "\n"


def render_json(nodes: list[dict]) -> str:
    return json.dumps({"generated_by": SCRIPT, "agents": nodes}, indent=2) + "\n"


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(description="Build the AGENTS.md map in .agents/map/.")
    parser.add_argument("--check", action="store_true",
                        help="exit 1 if the map is missing or out of date, without writing")
    parser.add_argument("--root", type=Path, default=Path(__file__).resolve().parents[2],
                        help="repository root (default: two levels above this script)")
    args = parser.parse_args(argv)
    root = args.root.resolve()

    nodes = read_graph(root)
    outputs = dict(zip(OUTPUTS, (render_json(nodes), render_markdown(nodes))))

    if args.check:
        stale = [p for p, text in outputs.items()
                 if not (root / p).is_file() or (root / p).read_text(encoding="utf-8") != text]
        for p in stale:
            print(f"{p}: out of date")
        print("AGENTS.md map is " + ("out of date" if stale else "up to date"))
        return 1 if stale else 0

    for p, text in outputs.items():
        (root / p).parent.mkdir(parents=True, exist_ok=True)
        (root / p).write_text(text, encoding="utf-8")
        print(f"wrote {p}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
